### ISSUE TITLE
Formatting of practice files.

### ISSUE THREAD

**Issue by ash2shukla** [RafaelBroseghini/PyPractice#15]
I have two suggestions regarding the Formatting of the practice files.

1. I found the header String to be a bit non-standard.

__ author __ is assigned the author name mostly.
and the date and filename can be generated if needed by __ file __ and os.path.getmtime(__ file __).
If needed then other meta information can be given as __ excercise __.

```python
__author__="John Doe"
__excercise__="Strings" # optional
__date__ ="12/12/1234"  # optional
```

2. I suggest giving the problem statement as a docstring to a function as it makes it much less ambiguous that where should a particular question's answer should be given.
Take this for instance-

```python
"""some question"""

def taskx():
    pass

"""some other question"""

def tasky():
    pass
```

```python
def taskx():
    """some question"""
    pass

def tasky():
    """some other question"""
    pass
```

The latter looks more neat to me.

**Comment by RafaelBroseghini** [comment]
Would you mind changing that around ? At this point we only have exercises for strings lists and dicts, so would not be much. Thanks!

**Comment by ash2shukla** [comment]
No problem. I just thought it would be better to raise issue than creating PR right away.

**Comment by RafaelBroseghini** [comment]
Awesome! Thank you so much.

**Comment by ash2shukla** [comment]
#16 Fixed.
